### ISSUE TITLE
EndeavourOS support?

### ISSUE THREAD

**Issue by Iceburgino** [uwzis/GPU-Passthrough-Manager#27] opened 2022-12-29 13:29 UTC
If I use this program on EOS, I don't notice any changes made to my grub and initramfs. Is EOS supported?

**Comment by Iceburgino** [comment] 2022-12-29 14:01
I examined the scripts in the repo real quick, seems like for my case (dracut) there is no code. So the answer's probably no?

**Comment by MarioGK** [comment] 2022-12-29 16:42
Yeah i would like to know if this supports dracut and the newest endeouveros

**Comment by ghost** [comment] 2022-12-29 17:03
> If I use this program on EOS, I don't notice any changes made to my grub and initramfs. Is EOS supported?

EndeavourOS is Arch based and to my knowledge is the same exact distro Uwzis uses to build/test this repository. I use just Arch and it works just fine. So to answer this, not only yes, but it was designed for it.

> I examined the scripts in the repo real quick, seems like for my case (dracut) there is no code. So the answer's probably no?

Dracut is not currently officially supported which would be your problem. However, #25 fixes this and should add dracut support in the scripts.

**Comment by MarioGK** [comment] 2022-12-29 17:20
@89mpxf What is it needed so that #25 gets merged? tests or some other feature?

**Comment by ghost** [comment] 2022-12-29 17:26
> @89mpxf What is it needed so that #25 gets merged? tests or some other feature?

I'm not sure why it hasn't been merged, I guess it hasn't been properly tested yet. I reviewed it and I'm pretty sure it worked for the guy who pushed it, so you're more than welcome to test his fork and also sign off on it.

**Comment by Iceburgino** [comment] 2022-12-29 17:36
@89mpxf thanks for your reply. I tried the patches made in #25, but after that, the result of `lspci -k`  looks like this:
```
01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
        Subsystem: Lenovo Device 3e85
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia
01:00.1 Audio device: NVIDIA Corporation GA106 High Definition Audio Controller (rev a1)
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
```

So I guess it's not only dracut being unsupported that causes the issues.

**Comment by ghost** [comment] 2022-12-29 17:42
> @89mpxf thanks for your reply. I tried the patches made in #25, but after that, the result of `lspci -k` looks like this:
> 
> ```
> 01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
>         Subsystem: Lenovo Device 3e85
>         Kernel driver in use: nvidia
>         Kernel modules: nouveau, nvidia_drm, nvidia
> 01:00.1 Audio device: NVIDIA Corporation GA106 High Definition Audio Controller (rev a1)
>         Kernel driver in use: snd_hda_intel
>         Kernel modules: snd_hda_intel
> ```
> 
> So I guess it's not only dracut being unsupported that causes the issues.

I am going to fork the repository and open a new dracut compatibility PR. I should have a fix for you soon

**Comment by Iceburgino** [comment] 2022-12-29 17:54
@89mpxf thanks a lot. Btw, maybe it will be useful for you - the program doesn't seem to add intel_iommu=on for me. Even after adding it manually, the situation doesn't change.

I have tried other methods, including the script one, adding files to modprobe and to modules-load, but had no success. The furthest I could get is to make the audio device appear with vfio-pci and video to stay with nvidia.

Even the manual methods don't seem to do much for me.

**Comment by ghost** [comment] 2022-12-29 17:57
> @89mpxf thanks a lot. Btw, maybe it will be useful for you - the program doesn't seem to add intel_iommu=on for me. Even after adding it manually, the situation doesn't change.
> 
> I have tried other methods, including the script one, adding files to modprobe and to modules-load, but had no success. The furthest I could get is to make the audio device appear with vfio-pci and video to stay with nvidia.
> 
> Even the manual methods don't seem to do much for me.

No problem :) What bootloader do you use though? It attempts to set kernel parameters through the system bootloader.

**Comment by Iceburgino** [comment] 2022-12-29 17:59
I use grub

**Comment by ghost** [comment] 2022-12-29 18:02
> I use grub

Does adding intel_iommu=on manually actually enable IOMMU? Also, try running the first time setup script in #28, very little needs to be done to force driver loading via dracut.

**Comment by uwzis** [comment] 2022-12-29 18:07
I just added the dracut support, I designed the original package around endeavorOS when they used mkinitcpio but the changed it to dracut... I dont know why they did that but I prefer mkinit.

**Comment by Iceburgino** [comment] 2022-12-29 18:11
Yes, I can see `IOMMU: enabled` in `dmesg`.

Can I just run the program again after deleting data.json and including the new patches in #28? Or do I need to remove the previous config the program made after the last run?

**Comment by Iceburgino** [comment] 2022-12-29 18:23
I tried the newer version, but it doesn't have an effect on the output of `lspci -k` I listed above.

**Comment by uwzis** [comment] 2022-12-29 18:31
It sounds like its an issue loading Vfio modules. Can you run "cat /etc/modprobe.d/vfio.conf"? It should show the ids of the nvidia card

**Comment by uwzis** [comment] 2022-12-29 18:33
What other graphics device do you have in your system?

**Comment by Iceburgino** [comment] 2022-12-29 18:35
> It sounds like its an issue loading Vfio modules. Can you run "cat /etc/modprobe.d/vfio.conf"? It should show the ids of the nvidia card

The output:
```
options vfio-pci ids=10de:228e,10de:2560%
 ```




> What other graphics device do you have in your system?

Also intel (Intel TigerLake-H GT1 [UHD Graphics] )

**Comment by uwzis** [comment] 2022-12-29 18:55
The percent sign at the end shouldn't be there, that might be the problem

**Comment by Iceburgino** [comment] 2022-12-29 18:56
> The percent sign at the end shouldn't be there, that might be the problem

It's actually weird, I don't see this in the file opened with gedit. It isn't there.

**Comment by uwzis** [comment] 2022-12-29 18:58
Then make a vfio.conf in the modprobe.d directory and paste the options you cated

**Comment by uwzis** [comment] 2022-12-29 19:00
Then remake your dracut and it should work as long as the vfio modules are loaded

**Comment by uwzis** [comment] 2022-12-29 19:02
I dont use initramfs but they have to have vfio modules enabled in the conf file for it. I would look up how to add vfio modules to initramfs

**Comment by Iceburgino** [comment] 2022-12-29 19:33
> I dont use initramfs but they have to have vfio modules enabled in the conf file for it. I would look up how to add vfio modules to initramfs

I thing I get [what you mean](https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Loading_vfio-pci_early:~:text=the%20initramfs.-,dracut,-Following%20the%20same), but I tried that, and somehow dracut refuses to load these modules. I tried through configuration using `modules-load.d` but it loads only vfio-pci (it's the first in the list). 

Btw, after `modules-load.d` I get:

```
01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
        Subsystem: Lenovo Device 3e85
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia
01:00.1 Audio device: NVIDIA Corporation GA106 High Definition Audio Controller (rev a1)
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel
```

**Comment by Iceburgino** [comment] 2022-12-29 19:59
@uwzis You've said you have tested gpu-passthrough-manager on EOS to begin with. Does it work for you? Because if it does I probably should stop wasting your time and try and fix problems specific to my machine.

**Comment by uwzis** [comment] 2022-12-29 20:55
I tested it before when it used mkinitcpio, since the vfio-pci driver is loaded, the audio device is ready but your gpu isn't, it may have to do with your card being a max-Q SQU. these cards are infamous for their restrictions in firmware. mpxf has a laptop with a 1070 max-Q and it let him pass through the card to windows but drivers wouldnt download because of a code 43. I don't think it would not let you load vfio unless its changed how nvidia writes their firmware. Another theory I have is its not loading because vfio wont load the vfio-pci driver if you only have one display output to a monitor, Do you use optimus manager?

**Comment by uwzis** [comment] 2022-12-29 20:57
It is very possible that the max-Q card will not have access to the drivers even if vfio is loaded so it may not even work... I have seen some people "mod" their firmware but I havent done it before.

**Comment by Iceburgino** [comment] 2022-12-29 21:07
> It is very possible that the max-Q card will not have access to the drivers even if vfio is loaded so it may not even work... I have seen some people "mod" their firmware but I havent done it before.

I think it's important to mention for context that I switched from manjaro, where I had a perfectly functional passthrough setup. But again, that was using mkinitcpio, as you said... 

So I don't think my card is the issue.

By the way, @89mpxf was asking -  enabling iommu in grub does not make any difference, since without this option, this happens:
```
DMAR: Intel-IOMMU force enabled due to platform opt in
```

**Comment by uwzis** [comment] 2022-12-29 21:41
Do drivers install on a virtual machine on the 3060 max-Q?

**Comment by Iceburgino** [comment] 2022-12-29 21:45
> Do drivers install on a virtual machine on the 3060 max-Q?

Yes, they did when I was on manjaro (i technically still can do that, it's just that I can't pass through my gpu on EOS). I've even tried gaming on it, and got pretty close to native (some performance was lost due to looking glass)

**Comment by uwzis** [comment] 2022-12-29 21:48
It is actually faster than native, linux will manager memory better than windows... as long as your CPU topology is correct you should get better than native minus the looking glass tradeoff. I got 20% or more performance on most applications with a 12900k and my 3080ti I have passed to the windows VM is in a x4 slot.

**Comment by Iceburgino** [comment] 2022-12-29 21:51
Anyway, as far as I see, EOS has just switched to dracut. So I'm probably one of the first to have been impacted. I think I need to open a topic at their forum about this.

**Comment by uwzis** [comment] 2022-12-29 21:55
I will do some testing later on this issue. I will report my results to this thread. Thank you for opening the forum

**Comment by ajgringo619** [comment] 2022-12-29 21:59
I also use EOS and just made the switch to dracut. For my GTX 1660 card, I created **/etc/dracut.conf.d/vfio.conf** with this:
```
force_drivers+=" vfio_pci vfio_virqfd vfio_iommu_type1 vfio crc32c "
```
In **/etc/mkinitcpio.conf**, this was:
```
MODULES="vfio_pci vfio_virqfd vfio_iommu_type1 vfio crc32c"
```
So far, so good.

**Comment by Iceburgino** [comment] 2022-12-29 22:03
Wha... You can actually just use mkinitcpio.conf? Let me try that real quick...

**Comment by Iceburgino** [comment] 2022-12-29 22:08
> I also use EOS and just made the switch to dracut. For my GTX 1660 card, I created **/etc/dracut.conf.d/vfio.conf** with this:
> 
> ```
> force_drivers+=" vfio_pci vfio_virqfd vfio_iommu_type1 vfio crc32c "
> ```
> 
> In **/etc/mkinitcpio.conf**, this was:
> 
> ```
> MODULES="vfio_pci vfio_virqfd vfio_iommu_type1 vfio crc32c"
> ```
> 
> So far, so good.

This doesn't work for me. If I don't do anything in modules-load.d, even the audio device doesn't get passed.

**Comment by ajgringo619** [comment] 2022-12-30 01:07
Never had anything in /etc/modules-load.d. My **vfio.conf** for the modules is in **/etc/modprobe.d**:
```
options vfio-pci ids=10de:21c4,10de:1aeb,10de:1aec,10de:1aed
```

**Comment by Iceburgino** [comment] 2022-12-30 13:01
> Never had anything in /etc/modules-load.d. My **vfio.conf** for the modules is in **/etc/modprobe.d**:
> 
> ```
> options vfio-pci ids=10de:21c4,10de:1aeb,10de:1aec,10de:1aed
> ```

I have that too, but still, it's not working.

**Comment by Iceburgino** [comment] 2022-12-30 15:55
Update on this. People at the EOS forum [told me](https://forum.endeavouros.com/t/gpu-passthrough-on-cassini/35420/18) that you should use `sudo dracut-rebuild` instead of `sudo dracut -f` to get it working. This is relevant if you use grub.

There's a [wiki](https://discovery.endeavouros.com/installation/dracut/2022/12/) page for this.

**Comment by uwzis** [comment] 2022-12-30 23:01
> Update on this. People at the EOS forum [told me](https://forum.endeavouros.com/t/gpu-passthrough-on-cassini/35420/18) that you should use `sudo dracut-rebuild` instead of `sudo dracut -f` to get it working. This is relevant if you use grub.
> 
> There's a [wiki](https://discovery.endeavouros.com/installation/dracut/2022/12/) page for this.

So I should change dracut -f to dracut-rebuild to resolve this issue?

**Comment by Iceburgino** [comment] 2022-12-30 23:36
> So I should change dracut -f to dracut-rebuild to resolve this issue?

I think it will break the app for all the people who use dracut but who are not on EOS. Fedora, as you've seen, actually doesn't need this command, it's fine with `dracut -f`. So you need it only for EOS. My guess is this command is from `eos-dracut` package, it's not present in other distros (nor should it probably be).

**Comment by ajgringo619** [comment] 2022-12-30 23:43
It's just a script that loops through all kernels to create the initramfs for each:
```
while read -r pkgbase; do
    kernelversion=$(basename "${pkgbase%/pkgbase}")
    kernelname=$(cat "${pkgbase}")
    echo "Running dracut for ${kernelname}-${kernelversion}"
    dracut --force --hostonly --no-hostonly-cmdline "/boot/initramfs-${kernelname}.img" "${kernelversion}"
    dracut --force --no-hostonly "/boot/initramfs-${kernelname}-fallback.img" "${kernelversion}"
done < <(find /usr/lib/modules -maxdepth 2 -type f -name pkgbase)
```
As you can see, it _does_ use 'dracut -f' (short for 'dracut --force'), but it specifies the exact location of the generated file.

**Comment by uwzis** [comment] 2022-12-31 17:52
After looking into this issue, I have realized how much I hate Dracut. I love mkinitcpio and I have an understanding that it inst being maintained, but it just works. I would appreciate if someone can add the required commands to get this working to the bottom of fts.sh in the Dracut section.

**Comment by Iceburgino** [comment] 2023-01-01 17:58
I think dracut just annoys people because it's a new thing and you need to adapt. It takes time and effort, and, understandably, not everyone has it. But we can't stay in the past forever. 

To me, the way pci passthrough is done with dracut is quite simple and elegant. When you have things separate in files, it feels more clean and organized.

It's just that EndeavourOS has changed the default way to rebuild initramfs image with dracut.

Anyway, I'll add the necessary code, but you'll probably need to add `lsb-release` as a dependency (it lets you know which distro you use when you run `lsb_release -is`).

**Comment by Iceburgino** [comment] 2023-01-01 19:20
Done! Added support for EndeavourOS Cassini in #31. The others that use different distros will need to test it and see if just plain `dracut -f` works.

**Comment by uwzis** [comment] 2023-01-01 20:06
I reviewed it and merged it to main. This should add support for many more systems. I will do some testing and come back with my results.

**Closed as completed** 2023-01-01 22:14 UTC
